// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtLkoD6HKjwUB1maewJTBpepJs4s5RbAo',
    appId: '1:100731098453:web:384fe89fededcd00b78bdc',
    messagingSenderId: '100731098453',
    projectId: 'loginpage-b65af',
    authDomain: 'loginpage-b65af.firebaseapp.com',
    storageBucket: 'loginpage-b65af.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACQmnpGJivDF0T9BH4ucRM3Z9ROr4qIWo',
    appId: '1:100731098453:android:280f2ba4fa0a7befb78bdc',
    messagingSenderId: '100731098453',
    projectId: 'loginpage-b65af',
    storageBucket: 'loginpage-b65af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmtpmxiB2MBM_ujIvHVgTY2zgXRtmXlg0',
    appId: '1:100731098453:ios:509e053cbfaf1709b78bdc',
    messagingSenderId: '100731098453',
    projectId: 'loginpage-b65af',
    storageBucket: 'loginpage-b65af.appspot.com',
    iosBundleId: 'com.example.healthFirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmtpmxiB2MBM_ujIvHVgTY2zgXRtmXlg0',
    appId: '1:100731098453:ios:404a4290089a98d3b78bdc',
    messagingSenderId: '100731098453',
    projectId: 'loginpage-b65af',
    storageBucket: 'loginpage-b65af.appspot.com',
    iosBundleId: 'com.example.healthFirst.RunnerTests',
  );
}
